var NAVTREE =
[
  [ "pyManga", "index.html", [
    [ " [input]MangaProject", "project_dox__MangaProject__MangaProject.html", "project_dox__MangaProject__MangaProject" ],
    [ "please_read", "md_TreeModelLib_BelowgroundCompetition_OGS_please_read.html", null ],
    [ "_index", "md_web_content_de_docs__index.html", null ],
    [ "_index", "md_web_content_de_docs_Erste_Schritte__index.html", null ],
    [ "MacOS", "md_web_content_de_docs_Erste_Schritte_MacOS.html", null ],
    [ "Ubuntu", "md_web_content_de_docs_Erste_Schritte_Ubuntu.html", null ],
    [ "Windows", "md_web_content_de_docs_Erste_Schritte_Windows.html", null ],
    [ "search", "md_web_content_de_search.html", null ],
    [ "_index", "md_web_content_en_docs__index.html", null ],
    [ "_index", "md_web_content_en_docs_getting_started__index.html", null ],
    [ "MacOS", "md_web_content_en_docs_getting_started_MacOS.html", null ],
    [ "Ubuntu", "md_web_content_en_docs_getting_started_Ubuntu.html", null ],
    [ "Windows", "md_web_content_en_docs_getting_started_Windows.html", null ],
    [ "search", "md_web_content_en_search.html", null ],
    [ "Contributor Covenant Code of Conduct", "md_web_themes_docsy_assets_vendor_bootstrap_CODE_OF_CONDUCT.html", null ],
    [ "callout-danger-async-methods", "md_web_themes_docsy_assets_vendor_bootstrap_site__includes_callout-danger-async-methods.html", null ],
    [ "callout-info-mediaqueries-breakpoints", "md_web_themes_docsy_assets_vendor_bootstrap_site__includes_callout-info-mediaqueries-breakpoints.html", null ],
    [ "callout-warning-color-assistive-technologies", "md_web_themes_docsy_assets_vendor_bootstrap_site__includes_callout-warning-color-assistive-technologies.html", null ],
    [ "brand", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_about_brand.html", null ],
    [ "license", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_about_license.html", null ],
    [ "overview", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_about_overview.html", null ],
    [ "translations", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_about_translations.html", null ],
    [ "browser-bugs", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_browser-bugs.html", null ],
    [ "alerts", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_alerts.html", null ],
    [ "badge", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_badge.html", null ],
    [ "breadcrumb", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_breadcrumb.html", null ],
    [ "button-group", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_button-group.html", null ],
    [ "buttons", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_buttons.html", null ],
    [ "card", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_card.html", null ],
    [ "carousel", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_carousel.html", null ],
    [ "collapse", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_collapse.html", null ],
    [ "dropdowns", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_dropdowns.html", null ],
    [ "forms", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_forms.html", null ],
    [ "input-group", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_input-group.html", null ],
    [ "jumbotron", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_jumbotron.html", null ],
    [ "list-group", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_list-group.html", null ],
    [ "modal", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_modal.html", null ],
    [ "navbar", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_navbar.html", null ],
    [ "navs", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_navs.html", null ],
    [ "pagination", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_pagination.html", null ],
    [ "popovers", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_popovers.html", null ],
    [ "progress", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_progress.html", null ],
    [ "scrollspy", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_scrollspy.html", null ],
    [ "tooltips", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_components_tooltips.html", null ],
    [ "code", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_content_code.html", null ],
    [ "figures", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_content_figures.html", null ],
    [ "images", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_content_images.html", null ],
    [ "reboot", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_content_reboot.html", null ],
    [ "tables", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_content_tables.html", null ],
    [ "typography", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_content_typography.html", null ],
    [ "approach", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_extend_approach.html", null ],
    [ "icons", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_extend_icons.html", null ],
    [ "index", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_extend_index.html", null ],
    [ "accessibility", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_getting-started_accessibility.html", null ],
    [ "best-practices", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_getting-started_best-practices.html", null ],
    [ "browsers-devices", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_getting-started_browsers-devices.html", null ],
    [ "build-tools", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_getting-started_build-tools.html", null ],
    [ "contents", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_getting-started_contents.html", null ],
    [ "download", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_getting-started_download.html", null ],
    [ "introduction", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_getting-started_introduction.html", null ],
    [ "javascript", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_getting-started_javascript.html", null ],
    [ "theming", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_getting-started_theming.html", null ],
    [ "webpack", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_getting-started_webpack.html", null ],
    [ "grid", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_layout_grid.html", null ],
    [ "media-object", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_layout_media-object.html", null ],
    [ "overview", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_layout_overview.html", null ],
    [ "utilities-for-layout", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_layout_utilities-for-layout.html", null ],
    [ "migration", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_migration.html", null ],
    [ "`.", "size.html", null ],
    [ "borders", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_borders.html", null ],
    [ "clearfix", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_clearfix.html", null ],
    [ "close-icon", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_close-icon.html", null ],
    [ "colors", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_colors.html", null ],
    [ "display", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_display.html", null ],
    [ "embed", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_embed.html", null ],
    [ "flex", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_flex.html", null ],
    [ "float", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_float.html", null ],
    [ "image-replacement", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_image-replacement.html", null ],
    [ "position", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_position.html", null ],
    [ "screenreaders", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_screenreaders.html", null ],
    [ "shadows", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_shadows.html", null ],
    [ "sizing", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_sizing.html", null ],
    [ "spacing", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_spacing.html", null ],
    [ "text", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_text.html", null ],
    [ "vertical-align", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_vertical-align.html", null ],
    [ "visibility", "md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_visibility.html", null ],
    [ "Change Log", "md_web_themes_docsy_assets_vendor_Font-Awesome_CHANGELOG.html", null ],
    [ "Contributor Covenant Code of Conduct", "md_web_themes_docsy_assets_vendor_Font-Awesome_CODE_OF_CONDUCT.html", null ],
    [ "Contributing to Font Awesome", "md_web_themes_docsy_assets_vendor_Font-Awesome_CONTRIBUTING.html", null ],
    [ "Upgrading Guide", "md_web_themes_docsy_assets_vendor_Font-Awesome_UPGRADING.html", null ],
    [ "How to Contribute", "md_web_themes_docsy_CONTRIBUTING.html", null ],
    [ "readfile", "md_web_themes_docsy_layouts_shortcodes_readfile.html", null ],
    [ "_index", "md_web_themes_docsy_userguide_content_en_about__index.html", null ],
    [ "_index", "md_web_themes_docsy_userguide_content_en_community__index.html", null ],
    [ "_index", "md_web_themes_docsy_userguide_content_en_docs__index.html", null ],
    [ "_index", "md_web_themes_docsy_userguide_content_en_docs_Adding_content__index.html", null ],
    [ "content", "md_web_themes_docsy_userguide_content_en_docs_Adding_content_content.html", null ],
    [ "feedback", "md_web_themes_docsy_userguide_content_en_docs_Adding_content_feedback.html", null ],
    [ "iconsimages", "md_web_themes_docsy_userguide_content_en_docs_Adding_content_iconsimages.html", null ],
    [ "lookandfeel", "md_web_themes_docsy_userguide_content_en_docs_Adding_content_lookandfeel.html", null ],
    [ "navigation", "md_web_themes_docsy_userguide_content_en_docs_Adding_content_navigation.html", null ],
    [ "repository-links", "md_web_themes_docsy_userguide_content_en_docs_Adding_content_repository-links.html", null ],
    [ "index", "md_web_themes_docsy_userguide_content_en_docs_Adding_content_Shortcodes_index.html", null ],
    [ "versioning", "md_web_themes_docsy_userguide_content_en_docs_Adding_content_versioning.html", null ],
    [ "_index", "md_web_themes_docsy_userguide_content_en_docs_Best_practices__index.html", null ],
    [ "organizing-content", "md_web_themes_docsy_userguide_content_en_docs_Best_practices_organizing-content.html", null ],
    [ "site-guidance", "md_web_themes_docsy_userguide_content_en_docs_Best_practices_site-guidance.html", null ],
    [ "_index", "md_web_themes_docsy_userguide_content_en_docs_Contribution_guidelines__index.html", null ],
    [ "_index", "md_web_themes_docsy_userguide_content_en_docs_Deployment__index.html", null ],
    [ "_index", "md_web_themes_docsy_userguide_content_en_docs_Examples__index.html", null ],
    [ "_index", "md_web_themes_docsy_userguide_content_en_docs_Getting_started__index.html", null ],
    [ "_index", "md_web_themes_docsy_userguide_content_en_docs_Language__index.html", null ],
    [ "_index", "md_web_themes_docsy_userguide_content_en_docs_Updating__index.html", null ],
    [ "search", "md_web_themes_docsy_userguide_content_en_search.html", null ],
    [ "How to Contribute", "md_web_themes_docsy_userguide_CONTRIBUTING.html", null ],
    [ "Classes", "annotated.html", [
      [ "Class List", "annotated.html", "annotated_dup" ],
      [ "Class Index", "classes.html", null ],
      [ "Class Hierarchy", "hierarchy.html", "hierarchy" ]
    ] ],
    [ "Examples", "examples.html", "examples" ]
  ] ]
];

var NAVTREEINDEX =
[
".html",
"classpyMANGA_1_1TreeModelLib_1_1BelowgroundCompetition_1_1OGSLargeScale3D_1_1OGSLargeScale3D_1_1OGSLargeScale3D.html#a66ecf78230bda4aa99edf4a623af642a",
"md_web_themes_docsy_assets_vendor_bootstrap_site_docs_4.1_utilities_spacing.html"
];

var SYNCONMSG = 'click to disable panel synchronisation';
var SYNCOFFMSG = 'click to enable panel synchronisation';